### ISSUE TITLE
🤔 Submitting a form that does not redirect

### ISSUE THREAD

**Issue by iamvery** [iamvery/iamvery-elixir#16]
# Problem

Right now the `submit_form` function [assumes](https://github.com/iamvery/iamvery-elixir/blob/aac322e8200790c609e40165faf85232c7c6622f/lib/iamvery/phoenix/live_view/test_helpers.ex#L92) that the response is a redirect. This may not be the case.

How should we handle form submissions that do not redirect?

# (Potential) Solution(s)

One option would be to check the response and behave accordingly.

```elixir
def submit_form({conn, {:ok, view, _html}}, selector, attributes) do
  result = view |> form(selector, attributes) |> render_submit()

  case result do
    {:error, _} -> {conn, follow_redirect(html, conn)}
    _ -> {conn, {:ok, view, result}}
  end
end
```

Another option would be to remove the assumption and require an explicit "follow" from the caller. I tend to not prefer this option, because the whole purpose of this lib is to minimize required knowledge of underlying live-view-isms.

**Comment by sodapopcan** [comment]
`follow_redirect` takes an optional third arg that asserts it redirected to the correct URL so it would be nice to be set that up.

You could have a `follow_submit_form` as well?  You could also probably just get away with `submit` and `follow_submit` since they'd be taking a selector that _hopefully_ makes it obvious it's a form:


```elixir
|> follow_submit("form", %{
  pizza: %{
    toppings: %{
      0 => %{
        name: "Some topping everyone likes and no one will complain about"
      }
    }
  }
}, ~p"/thank-you")
```

**Comment by iamvery** [comment]
Very cool! I'm not sure I've seen the follow_redirect/3 form. I've also updated `submit_form` in #23 to handle redirects internally. The path option would be a nice addition.
