### ISSUE TITLE
Click vs. Follow?

### ISSUE THREAD

**Issue by iamvery** [iamvery/iamvery-elixir#17]
Is the distinction of `click` vs. `follow` necessary? By and large, the purpose of the library is to hide these details. Can we avoid leaking them by matching return values and doing what is needed? https://github.com/iamvery/iamvery-elixir/blob/aac322e8200790c609e40165faf85232c7c6622f/test/iamvery/phoenix/live_view/test_helpers_test.exs#L55

**Comment by sodapopcan** [comment]
Ah sorry, I'll read through the PR before commenting further.
